In [1]:
# Importing the libraries 
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

import warnings
warnings.filterwarnings('ignore')
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
# Importing the datasetm
dataset = pd.read_csv(r'C:\Users\IDEAPAD 320\Desktop\datasets\Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values


In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X


array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [5]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

from sklearn.compose import ColumnTransformer



labelencoder_X_2 = LabelEncoder()

X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])



columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [1])], remainder='passthrough')

X = np.array(columnTransformer.fit_transform(X), dtype = np.str)

X = X[:, 1:]


In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() 
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test) 

In [10]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.


In [11]:
# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu', input_dim = 11))


# Adding the second hidden layer
classifier.add(Dense(output_dim = 6, init = 'uniform', activation = 'relu'))


# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

Instructions for updating:
Colocations handled automatically by placer.


In [12]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 100)

Instructions for updating:
Use tf.cast instead.
Epoch 1/100
8000/8000 [==============================] - 2s 269us/step - loss: 0.4753 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.4263 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 198us/step - loss: 0.4206 - acc: 0.8060
Epoch 4/100
8000/8000 [==============================] - 2s 230us/step - loss: 0.4175 - acc: 0.8242
Epoch 5/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.4153 - acc: 0.8285
Epoch 6/100
8000/8000 [==============================] - 2s 259us/step - loss: 0.4133 - acc: 0.8304
Epoch 7/100
8000/8000 [==============================] - 2s 254us/step - loss: 0.4119 - acc: 0.8341
Epoch 8/100
8000/8000 [==============================] - 2s 253us/step - loss: 0.4109 - acc: 0.8345
Epoch 9/100
8000/8000 [==============================] - 2s 252us/step - loss: 0.4094 - acc: 0.8330
Epoch 10/100
8000/8000 [============================

8000/8000 [==============================] - 1s 164us/step - loss: 0.3998 - acc: 0.8346
Epoch 80/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.4000 - acc: 0.8339
Epoch 81/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.4004 - acc: 0.8350
Epoch 82/100
8000/8000 [==============================] - 2s 243us/step - loss: 0.3998 - acc: 0.8352
Epoch 83/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4006 - acc: 0.8369
Epoch 84/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.3997 - acc: 0.8335
Epoch 85/100
8000/8000 [==============================] - 2s 222us/step - loss: 0.4006 - acc: 0.8356
Epoch 86/100
8000/8000 [==============================] - 2s 200us/step - loss: 0.4008 - acc: 0.8337
Epoch 87/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.4001 - acc: 0.8331
Epoch 88/100
8000/8000 [==============================] - 2s 192us/step - loss: 0.4002 - acc: 0.8347
Epo

In [13]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)



In [14]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [15]:
cm

array([[1559,   36],
       [ 281,  124]], dtype=int64)

In [16]:
correct_prediction = cm[0][0]+cm[1][1]
wrong_prediction = cm[0][1]+cm[1][0]
total = correct_prediction + wrong_prediction


In [17]:
correct_prediction

1683

In [18]:
wrong_prediction

317

In [19]:
accuracy = (correct_prediction/total)*100

In [20]:
accuracy

84.15